### PR TITLE
NOOS-649/prefix-css-classes

### PR DESCRIPTION
**Pull request by MattiaPrimavera**
# Description

**JIRA Reference**: [NOOS-649](https://noosenergy.atlassian.net/browse/NOOS-649)

[NOOS-649]: https://noosenergy.atlassian.net/browse/NOOS-649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by filiperosa — CHANGES_REQUESTED** [review]
👍
Working great, let's bump the version and merge!

**Review by filiperosa — CHANGES_REQUESTED** [review]
We also need to fix the error page which is not properly styled, we can copy it from the [gateway](https://github.com/noosenergy/noos-gateway/pull/280) which is already fixed.

Screenshot 2024-02-23 at 12 21 18

**Comment by MattiaPrimavera** [comment]
Did you manually force an error @filiperosa  ? 'Cause the page is correctly displaying on my side :

Screenshot 2024-02-23 at 15 20 51

**Comment by filiperosa** [comment]
> Did you manually force an error @filiperosa ? 'Cause the page is correctly displaying on my side :
> 
> >

No, just clicked the **Show error page** button. It displays correctly for you?
I double checked with a different browser and had the same result.

Same on the gateway, dash error page is broken while the [gateway's error page](https://app.noos.energy/dashboards/asdasd/) displays fine.

**Comment by MattiaPrimavera** [comment]
Thanks @filiperosa, it should be fixed now, waiting for the tests to pass :)

**Comment by MattiaPrimavera** [comment]
Bumped to version `2.0.1` @filiperosa

**Review by filiperosa — APPROVED** [review]
🚢

**Pull request merged**
